DROP TABLE IF EXISTS `nrw_2017`;
CREATE TABLE `nrw_2017` (
  `id` int(8) NOT NULL AUTO_INCREMENT,
  `party` varchar(10) NOT NULL,
  `votes` int(1) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=0 DEFAULT CHARSET=utf8;
